<?php
/**
 * Front page — Residencias Reef Cozumel.
 * Conversion-focused direct booking homepage.
 *
 * Positions Residencias Reef/Cozumel as the trust hook while creating a clear
 * upgrade path into higher-value Riviera Maya and Tulum private villa stays.
 *
 * @package ResidenciasReefCozumel
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

get_header();

$lvc_cpt  = lvc_config( 'cpt', 'villas' );
$lvc_req  = lvc_page_url( 'request' );
$lvc_arch = lvc_archive_url();
$lvc_wa   = lvc_whatsapp_url();

if ( ! function_exists( 'lvc_area_image' ) ) {
	function lvc_area_image( $slug ) {
		$q = new WP_Query( array(
			'post_type'      => lvc_config( 'cpt', 'villas' ),
			'posts_per_page' => 1,
			'fields'         => 'ids',
			'tax_query'      => array( array( 'taxonomy' => 'area', 'field' => 'slug', 'terms' => $slug ) ),
		) );
		$img = $q->have_posts() ? lvc_property_image( $q->posts[0], 'large' ) : '';
		wp_reset_postdata();
		return $img;
	}
}

$lvc_home_hero_img = lvc_field( 'home_hero_image_url', 'option' );
if ( ! $lvc_home_hero_img ) {
	$lvc_home_hero_term = get_term_by( 'slug', 'riviera-maya', 'area' );
	$lvc_home_hero_img  = $lvc_home_hero_term ? lvc_field( 'hero_image_url', $lvc_home_hero_term ) : '';
}
if ( ! $lvc_home_hero_img ) {
	$lvc_home_hero_img = lvc_area_image( 'riviera-maya' );
}

$lvc_area_cards = array(
	array( 'Cozumel', 'cozumel', '/cozumel/', 'Residencias Reef condos and island stays for divers, couples, and guests who want a relaxed beachfront base.' ),
	array( 'Tulum', 'tulum', '/tulum-villa-rentals/', 'Private villas across Tulum Beach, Soliman Bay, Tankah Bay, Tulum Town, Aldea Zama, La Veleta, and Sian Ka\'an.' ),
	array( 'Playa del Carmen', 'playa-del-carmen', '/playa-del-carmen/', 'Beachfront and Playacar villas close to dining, beach clubs, nightlife, shopping, and easy arrival logistics.' ),
	array( 'Akumal', 'akumal', '/akumal/', 'Bayfront and beachfront villas for families, snorkeling trips, quieter beach stays, and multi-generational groups.' ),
);

$lvc_tulum_areas = array(
	array( 'Soliman Bay', 'soliman-bay', '/soliman-bay/', 'Quiet beachfront villas north of Tulum, often chosen for family trips, calm water, chef service, and more privacy than the main beach zone.' ),
	array( 'Tulum Beach Zone', 'tulum-beach-zone', '/tulum-beach-zone-villas/', 'For guests who want the restaurants, beach clubs, wellness scene, and boutique-hotel atmosphere close by.' ),
	array( 'Tulum Town', 'tulum-town', '/tulum-town-jungle-villas/', 'Better value, easier logistics, restaurants, nightlife access, and more practical options for longer stays or flexible groups.' ),
	array( 'Tankah Bay', 'tankah-bay', '/tankah-bay/', 'Beachfront and bayfront villas between Tulum and Akumal, with a quieter residential feel and good access to snorkeling and cenotes.' ),
	array( 'Aldea Zama', 'aldea-zama', '/tulum-villa-rentals/', 'Modern private villas between Tulum Town and the beach road, often a good fit for groups that want style and convenience.' ),
	array( 'La Veleta', 'la-veleta', '/tulum-villa-rentals/', 'Contemporary villas and private homes with strong value for groups that prefer restaurants, nightlife, and town access.' ),
);

$lvc_collection_filters = array(
	array( 'All Villas', $lvc_arch ),
	array( 'Cozumel', home_url( '/cozumel/' ) ),
	array( 'Tulum', home_url( '/tulum-villa-rentals/' ) ),
	array( 'Soliman Bay', home_url( '/soliman-bay/' ) ),
	array( 'Tulum Town', home_url( '/tulum-town-jungle-villas/' ) ),
	array( 'Playa del Carmen', home_url( '/playa-del-carmen/' ) ),
	array( 'Akumal', home_url( '/akumal/' ) ),
	array( 'Puerto Aventuras', home_url( '/puerto-aventuras/' ) ),
);

$lvc_collections = array(
	array( 'Large-Group Villas', home_url( '/collections/large-groups/' ), 'Villas that sleep 12+ for reunions, weddings, and multi-family trips.' ),
	array( 'Villas with a Private Chef', home_url( '/collections/private-chef/' ), 'In-villa chef service across the Riviera Maya.' ),
	array( 'Beachfront Villas', home_url( '/collections/beachfront/' ), 'Direct beach and oceanfront access.' ),
	array( 'Family Villas', home_url( '/collections/family-villas/' ), 'Space, safety, and easy logistics for families.' ),
);
?>

<style>
	.lcv-home-modern{background:var(--lvc-bg);color:var(--lvc-soft);font-family:var(--lvc-font-body)}
	.lcv-home-modern *{box-sizing:border-box}.lcv-home-wrap{width:min(1480px,calc(100% - clamp(2rem,6vw,6rem)));margin:0 auto}.lcv-home-narrow{width:min(980px,calc(100% - clamp(2rem,6vw,6rem)));margin:0 auto}.lcv-home-section{padding:clamp(4rem,7vw,7rem) 0}.lcv-home-section--alt{background:var(--lvc-bg-alt);border-top:1px solid var(--lvc-border);border-bottom:1px solid var(--lvc-border)}.lcv-home-kicker{display:block;margin:0 0 .85rem;color:var(--lvc-accent);font-size:.68rem;font-weight:400;letter-spacing:.2em;text-transform:uppercase}.lcv-home-title{margin:0;font-family:var(--lvc-font-display);font-size:clamp(2rem,4vw,3.65rem);font-weight:200;line-height:1.12;color:var(--lvc-text)}.lcv-home-title em{font-style:italic;color:var(--lvc-accent)}.lcv-home-copy{color:var(--lvc-soft);font-size:clamp(.98rem,1.25vw,1.08rem);font-weight:300;line-height:1.82}.lcv-home-head{text-align:center;margin:0 auto clamp(2rem,4vw,3rem);max-width:900px}.lcv-home-head .lcv-home-copy{max-width:760px;margin:1rem auto 0}.lcv-home-btns{display:flex;flex-wrap:wrap;gap:.85rem;align-items:center}.lcv-home-btn{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:.85rem 1.45rem;border:1px solid var(--lvc-accent);background:var(--lvc-accent);color:#fff!important;font-size:.86rem;font-weight:500;border-radius:var(--lvc-radius)}.lcv-home-btn--ghost{background:transparent!important;border-color:rgba(255,255,255,.28);color:var(--lvc-text)!important}
	.lcv-home-hero{position:relative;min-height:min(720px,82vh);display:flex;align-items:center;isolation:isolate;padding:clamp(7rem,10vw,10rem) 0;background:var(--lvc-bg-deep) var(--home-hero-img,none) center/cover no-repeat}.lcv-home-hero:before{content:'';position:absolute;inset:0;z-index:-1;background:linear-gradient(90deg,rgba(10,12,15,.95),rgba(10,12,15,.72) 48%,rgba(10,12,15,.48)),linear-gradient(0deg,rgba(10,12,15,.9),rgba(10,12,15,.25) 52%,rgba(10,12,15,.64))}.lcv-home-hero__grid{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(300px,.42fr);gap:clamp(2rem,5vw,5rem);align-items:end}.lcv-home-hero h1{max-width:920px;margin:0;font-family:var(--lvc-font-display);font-size:clamp(2.55rem,5vw,5.15rem);font-weight:200;line-height:1.08;color:var(--lvc-text)}.lcv-home-hero h1 em{display:block;margin-top:.25rem;font-style:italic;color:var(--lvc-accent)}.lcv-home-hero__sub{max-width:780px;margin:1.35rem 0 0;color:rgba(243,243,241,.84);font-size:clamp(1rem,1.3vw,1.13rem);line-height:1.78}.lcv-home-hero__actions{margin-top:1.8rem}.lcv-home-match{background:linear-gradient(180deg,rgba(16,21,28,.95),rgba(10,12,15,.88));border:1px solid rgba(255,255,255,.14);padding:1.5rem;box-shadow:0 24px 70px rgba(0,0,0,.36)}.lcv-home-match h2{margin:0 0 .6rem;font-family:var(--lvc-font-display);font-weight:300;font-size:1.25rem;color:var(--lvc-text)}.lcv-home-match p{margin:0;color:var(--lvc-soft);font-size:.9rem;line-height:1.7}.lcv-home-match__facts{display:grid;grid-template-columns:1fr 1fr;gap:.65rem;margin:1.1rem 0}.lcv-home-match__fact{border:1px solid var(--lvc-border);background:rgba(255,255,255,.035);padding:.85rem}.lcv-home-match__fact strong{display:block;font-family:var(--lvc-font-display);font-size:1.45rem;font-weight:300;color:var(--lvc-text);line-height:1}.lcv-home-match__fact span{display:block;margin-top:.35rem;color:var(--lvc-muted);font-size:.66rem;letter-spacing:.12em;text-transform:uppercase}
	.lcv-proof{background:var(--lvc-bg-alt);border-top:1px solid var(--lvc-border);border-bottom:1px solid var(--lvc-border);padding:1.15rem 0}.lvc-proof__inner{display:flex;flex-wrap:wrap;justify-content:center;gap:.8rem}.lvc-proof__item{border:1px solid var(--lvc-border);padding:.6rem .85rem;color:var(--lvc-soft);font-size:.78rem;text-transform:uppercase}.lvc-proof__item strong{color:var(--lvc-accent);font-weight:500}.lcv-intro-grid{display:grid;grid-template-columns:minmax(0,.85fr) minmax(0,1.15fr);gap:clamp(2rem,5vw,5rem);align-items:center}.lcv-home-panel{border-left:1px solid var(--lvc-border);padding-left:clamp(1.5rem,3vw,3rem)}.lcv-home-panel ul{list-style:none;margin:1.35rem 0 0;padding:0;display:grid;gap:.8rem}.lcv-home-panel li{position:relative;padding-left:1.25rem;color:var(--lvc-soft);line-height:1.65}.lcv-home-panel li:before{content:'✓';position:absolute;left:0;color:var(--lvc-accent)}
	.lcv-path-grid,.lcv-compare{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.lcv-upgrade-grid,.lcv-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.lcv-concierge-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:.9rem}.lcv-path-card,.lcv-upgrade-card,.lcv-step,.lcv-concierge-card,.lcv-compare-card{background:var(--lvc-card);border:1px solid var(--lvc-border);padding:1.35rem}.lcv-path-card h3,.lcv-upgrade-card h3,.lcv-step h3,.lcv-concierge-card h3,.lcv-compare-card h3{margin:0 0 .6rem;font-family:var(--lvc-font-display);font-weight:300;color:var(--lvc-text)}.lcv-path-card p,.lcv-upgrade-card p,.lcv-step p,.lcv-concierge-card p{margin:0;color:var(--lvc-soft);line-height:1.65;font-size:.92rem}.lcv-upgrade-card span,.lcv-step__num{display:block;color:var(--lvc-accent);font-size:.72rem;letter-spacing:.14em;text-transform:uppercase;margin-bottom:.6rem}.lcv-compare-card ul{margin:0;padding:0;list-style:none;display:grid;gap:.7rem}.lcv-compare-card li{position:relative;padding-left:1.1rem;color:var(--lvc-soft);line-height:1.55}.lcv-compare-card li:before{content:'•';position:absolute;left:0;color:var(--lvc-accent)}
	.lcv-filter-pills{display:flex;flex-wrap:wrap;justify-content:center;gap:.65rem;margin:0 auto 2.2rem;max-width:1040px}.lcv-filter-pill{display:inline-flex;align-items:center;justify-content:center;border:1px solid var(--lvc-border);background:rgba(255,255,255,.025);color:var(--lvc-soft)!important;padding:.62rem .9rem;font-size:.78rem;letter-spacing:.08em;text-transform:uppercase}.lcv-filter-pill:hover{border-color:var(--lvc-accent);color:var(--lvc-accent)!important;background:var(--lvc-accent-soft)}.lcv-villa-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1.35rem}.lcv-home-pagination{display:flex;justify-content:center;align-items:center;gap:.45rem;margin-top:2.5rem;flex-wrap:wrap}.lcv-home-pagination .page-numbers{display:inline-flex;align-items:center;justify-content:center;min-width:42px;min-height:42px;padding:.55rem .8rem;border:1px solid var(--lvc-border);color:var(--lvc-soft);background:rgba(255,255,255,.02)}.lcv-home-pagination .page-numbers.current{background:var(--lvc-accent);border-color:var(--lvc-accent);color:#fff}
	.lcv-area-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem}.lcv-tulum-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.lcv-area-tile{position:relative;min-height:330px;display:flex;align-items:flex-end;padding:1.35rem;border:1px solid var(--lvc-border);background:var(--lvc-card) var(--area-img,none) center/cover no-repeat;overflow:hidden}.lcv-tulum-grid .lcv-area-tile{min-height:285px}.lcv-area-tile:before{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(10,12,15,.12),rgba(10,12,15,.92))}.lcv-area-tile__body{position:relative;z-index:1}.lcv-area-tile h3{margin:0;font-family:var(--lvc-font-display);font-size:1.35rem;font-weight:300;color:var(--lvc-text)}.lcv-area-tile p{margin:.55rem 0 0;color:var(--lvc-soft);font-size:.86rem;line-height:1.55}.lcv-area-tile span{display:block;margin-top:.85rem;color:var(--lvc-accent);font-size:.82rem}.lcv-final-cta{background:var(--lvc-bg-deep);border-top:1px solid rgba(255,255,255,.12);text-align:center}.lcv-final-cta .lcv-home-copy{max-width:680px;margin:1rem auto 1.6rem}.lcv-final-cta .lcv-home-btns{justify-content:center}
	.lcv-home-compare{text-align:center;max-width:760px;margin:2.2rem auto 0;color:var(--lvc-soft);font-size:.95rem;line-height:1.7}.lcv-home-compare a{color:var(--lvc-accent);text-decoration:underline;text-underline-offset:3px}.lcv-home-compare a:hover{color:var(--lvc-accent-hover)}
	@media(max-width:1100px){.lcv-home-hero__grid,.lcv-intro-grid,.lcv-path-grid,.lcv-compare{grid-template-columns:1fr}.lcv-area-grid,.lcv-villa-grid,.lcv-tulum-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.lcv-upgrade-grid,.lcv-concierge-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.lcv-home-panel{border-left:0;padding-left:0}}@media(max-width:720px){.lcv-home-wrap,.lcv-home-narrow{width:calc(100% - 2rem)}.lcv-home-hero{min-height:auto;padding:6rem 0 4rem}.lcv-home-hero h1{font-size:clamp(2.3rem,12vw,3.5rem)}.lcv-home-btns{display:grid;grid-template-columns:1fr}.lcv-home-match__facts,.lcv-area-grid,.lcv-steps,.lcv-concierge-grid,.lcv-villa-grid,.lcv-path-grid,.lcv-upgrade-grid,.lcv-tulum-grid,.lcv-compare{grid-template-columns:1fr}.lvc-proof__item{width:100%;text-align:center}.lcv-filter-pills{justify-content:flex-start}}
</style>

<main class="lvc-home-modern">
	<section class="lcv-home-hero" <?php echo $lvc_home_hero_img ? 'style="--home-hero-img:url(\'' . esc_url( $lvc_home_hero_img ) . '\')"' : ''; ?> aria-label="Residencias Reef Cozumel and private Riviera Maya villa rentals"><div class="lcv-home-wrap lcv-home-hero__grid"><div><span class="lcv-home-kicker"><?php echo esc_html( lvc_brand() ); ?></span><h1>Residencias Reef Cozumel &amp; Private Riviera Maya Villa Rentals <em>with Concierge Planning</em></h1><p class="lcv-home-hero__sub">Start with relaxed beachfront condos in Cozumel, or let us match your group with private villas in Tulum, Soliman Bay, Tulum Town, Playa del Carmen, Akumal, Puerto Aventuras, and beyond.</p><div class="lcv-home-btns lcv-home-hero__actions"><a class="lcv-home-btn" href="<?php echo esc_url( $lvc_req ); ?>">Submit Your Villa Request</a><a class="lcv-home-btn lcv-home-btn--ghost" href="<?php echo esc_url( $lvc_arch ); ?>">Browse Villas &amp; Condos</a></div></div><aside class="lcv-home-match"><h2>Tell us your dates. We will shortlist the right stay.</h2><p>Share your group size, dates, preferred area, and service needs. We will help decide whether a simple Cozumel condo or a higher-service private villa makes more sense.</p><div class="lcv-home-match__facts"><div class="lcv-home-match__fact"><strong>Direct</strong><span>No OTA markup</span></div><div class="lcv-home-match__fact"><strong>Local</strong><span>Villa guidance</span></div></div><a class="lcv-home-btn" href="<?php echo esc_url( $lvc_req ); ?>">Get Villa Matches</a></aside></div></section>

	<section class="lcv-proof"><div class="lcv-home-wrap lvc-proof__inner"><div class="lvc-proof__item"><strong>Cozumel condos</strong> for simple beachfront stays</div><div class="lvc-proof__item"><strong>Private villas</strong> for families &amp; groups</div><div class="lvc-proof__item"><strong>Tulum areas</strong> matched by trip style</div><div class="lvc-proof__item"><strong>Chef, transfers &amp; tours</strong> on request</div></div></section>

	<section class="lcv-home-section lcv-home-section--alt"><div class="lcv-home-wrap lcv-intro-grid"><div><span class="lcv-home-kicker">Direct Booking Collection</span><h2 class="lcv-home-title">Start with Cozumel. Upgrade into the right <em>Riviera Maya villa</em>.</h2></div><div class="lcv-home-panel lcv-home-copy"><p>Residencias Reef Cozumel is a useful entry point for couples, divers, and smaller groups who want a relaxed beachfront condo. But many travelers need more space, service, privacy, or a better location for a family trip, celebration, retreat, or luxury stay.</p><ul><li>Condos for simpler Cozumel stays with beach access and practical nightly rates.</li><li>Private villas for larger groups, chef service, private pools, events, and higher-service trips.</li><li>Clear guidance across Cozumel, Tulum, Soliman Bay, Tulum Town, Playa del Carmen, Akumal, and Puerto Aventuras.</li></ul></div></div></section>

	<section class="lcv-home-section"><div class="lcv-home-wrap"><header class="lcv-home-head"><span class="lcv-home-kicker">Two Booking Paths</span><h2 class="lcv-home-title">Choose the stay that fits <em>the real trip</em></h2><p class="lcv-home-copy">A beachfront condo can be perfect for a low-friction Cozumel stay. A private villa is usually the better fit when the group, budget, and service expectations are higher.</p></header><div class="lcv-path-grid"><article class="lcv-path-card"><span class="lcv-home-kicker">Cozumel Hook</span><h3>Residencias Reef condos</h3><p>Best for couples, small families, divers, and guests who want beach access, a kitchen, pool access, and a quieter island base without paying for a full private villa.</p><a class="lcv-home-btn lcv-home-btn--ghost" href="<?php echo esc_url( home_url( '/cozumel/' ) ); ?>">View Cozumel Stays</a></article><article class="lcv-path-card"><span class="lcv-home-kicker">Money Path</span><h3>Private Riviera Maya villas</h3><p>Better for families, larger groups, celebrations, retreats, and guests who want private pools, more bedrooms, chef service, staff, and a more exclusive setting.</p><a class="lcv-home-btn" href="<?php echo esc_url( $lvc_req ); ?>">Request Villa Matches</a></article></div></div></section>

	<section class="lcv-home-section lcv-home-section--alt"><div class="lcv-home-wrap"><header class="lcv-home-head"><span class="lcv-home-kicker">When to Upgrade</span><h2 class="lcv-home-title">When a private villa is <em>the better fit</em></h2><p class="lcv-home-copy">Condos are easy and affordable. Villas are where space, privacy, service, and trip value become much stronger.</p></header><div class="lcv-upgrade-grid"><article class="lcv-upgrade-card"><span>8+ Guests</span><h3>More bedrooms and privacy</h3><p>Groups usually need larger layouts, multiple living areas, private pools, and fewer shared spaces.</p></article><article class="lcv-upgrade-card"><span>Chef Service</span><h3>Meals become part of the stay</h3><p>Private villas work better for breakfast service, celebrations, dinners, groceries, and custom dining.</p></article><article class="lcv-upgrade-card"><span>Special Occasions</span><h3>Better for celebrations</h3><p>Birthdays, family reunions, retreats, and milestone trips need a property that supports the full experience.</p></article></div></div></section>

	<section class="lcv-home-section" id="feat"><div class="lcv-home-wrap"><header class="lcv-home-head"><span class="lcv-home-kicker">Villa Collection</span><h2 class="lcv-home-title">Browse luxury villas in the <em>Riviera Maya</em></h2><p class="lcv-home-copy">Start with the full villa grid, or jump into the area that best matches your trip.</p></header><nav class="lcv-filter-pills" aria-label="Villa collection filters"><?php foreach ( $lvc_collection_filters as $filter ) : ?><a class="lcv-filter-pill" href="<?php echo esc_url( $filter[1] ); ?>"><?php echo esc_html( $filter[0] ); ?></a><?php endforeach; ?></nav><?php $lvc_paged = max( 1, (int) get_query_var( 'paged' ), (int) get_query_var( 'page' ) ); $lvc_villas = new WP_Query( array( 'post_type' => $lvc_cpt, 'posts_per_page' => 9, 'post_status' => 'publish', 'orderby' => 'date', 'order' => 'DESC', 'paged' => $lvc_paged ) ); if ( $lvc_villas->have_posts() ) : ?><div class="lcv-villa-grid"><?php while ( $lvc_villas->have_posts() ) : $lvc_villas->the_post(); get_template_part( 'template-parts/card-property', null, array( 'id' => get_the_ID() ) ); endwhile; ?></div><?php if ( $lvc_villas->max_num_pages > 1 ) : ?><nav class="lcv-home-pagination" aria-label="Villa pagination"><?php echo wp_kses_post( paginate_links( array( 'total' => $lvc_villas->max_num_pages, 'current' => $lvc_paged, 'mid_size' => 1, 'prev_text' => '&larr;', 'next_text' => '&rarr;' ) ) ); ?></nav><?php endif; wp_reset_postdata(); endif; ?></div></section>

	<section class="lcv-home-section lcv-home-section--alt"><div class="lcv-home-wrap"><header class="lcv-home-head"><span class="lcv-home-kicker">Where to Stay</span><h2 class="lcv-home-title">Choose the right <em>Riviera Maya area</em></h2><p class="lcv-home-copy">The right villa starts with the right location. These are the areas most guests compare first.</p></header><div class="lcv-area-grid"><?php foreach ( $lvc_area_cards as $area ) : $area_img = lvc_area_image( $area[1] ); ?><a class="lcv-area-tile" href="<?php echo esc_url( home_url( $area[2] ) ); ?>" style="<?php echo $area_img ? '--area-img:url(' . esc_url( $area_img ) . ')' : ''; ?>"><div class="lcv-area-tile__body"><h3><?php echo esc_html( $area[0] ); ?></h3><p><?php echo esc_html( $area[3] ); ?></p><span>Explore <?php echo esc_html( $area[0] ); ?> &rarr;</span></div></a><?php endforeach; ?></div><p class="lcv-home-compare">Not sure which to choose? Compare <a href="<?php echo esc_url( home_url( '/cozumel-vs-tulum-vs-playa-del-carmen-villa-rentals/' ) ); ?>">Cozumel vs Tulum vs Playa del Carmen</a> or <a href="<?php echo esc_url( home_url( '/tulum-vs-playa-del-carmen-comparison-guide/' ) ); ?>">Tulum vs Playa del Carmen</a>.</p></div></section>

	<section class="lcv-home-section"><div class="lcv-home-wrap"><header class="lcv-home-head"><span class="lcv-home-kicker">Browse by Collection</span><h2 class="lcv-home-title">High-intent villa <em>collections</em></h2><p class="lcv-home-copy">These are the commercial pages guests use when they already know the kind of trip they want.</p></header><div class="lcv-area-grid"><?php foreach ( $lvc_collections as $collection ) : ?><a class="lcv-area-tile" href="<?php echo esc_url( $collection[1] ); ?>"><div class="lcv-area-tile__body"><h3><?php echo esc_html( $collection[0] ); ?></h3><p><?php echo esc_html( $collection[2] ); ?></p><span>Explore collection &rarr;</span></div></a><?php endforeach; ?></div></div></section>

	<section class="lcv-home-section lcv-home-section--alt"><div class="lcv-home-wrap"><header class="lcv-home-head"><span class="lcv-home-kicker">Tulum Villa Areas</span><h2 class="lcv-home-title">Tulum is not one market: <em>match the area to the trip</em></h2><p class="lcv-home-copy">For higher-value villa inquiries, the most important question is often whether the group should stay beachfront, close to restaurants, in a quieter bay, or in town.</p></header><div class="lcv-tulum-grid"><?php foreach ( $lvc_tulum_areas as $area ) : $area_img = lvc_area_image( $area[1] ); ?><a class="lcv-area-tile" href="<?php echo esc_url( home_url( $area[2] ) ); ?>" style="<?php echo $area_img ? '--area-img:url(' . esc_url( $area_img ) . ')' : ''; ?>"><div class="lcv-area-tile__body"><h3><?php echo esc_html( $area[0] ); ?></h3><p><?php echo esc_html( $area[3] ); ?></p><span>Explore <?php echo esc_html( $area[0] ); ?> villas &rarr;</span></div></a><?php endforeach; ?></div></div></section>

	<section class="lcv-home-section"><div class="lcv-home-wrap"><header class="lcv-home-head"><span class="lcv-home-kicker">Cozumel or Villa Upgrade</span><h2 class="lcv-home-title">Cozumel condo or <em>private villa?</em></h2><p class="lcv-home-copy">This comparison helps guests self-select, which protects the low-cost condo traffic while pushing qualified groups toward better villa inquiries.</p></header><div class="lcv-compare"><article class="lcv-compare-card"><h3>Choose a Cozumel condo if...</h3><ul><li>You are a couple, small family, or diving-focused group.</li><li>You want a simple beachfront base at a lower nightly rate.</li><li>You do not need chef service, a large private pool, or full villa staff.</li></ul></article><article class="lcv-compare-card"><h3>Choose a private villa if...</h3><ul><li>You need more bedrooms, privacy, and living space.</li><li>You want chef service, staff, groceries, transfers, or celebration planning.</li><li>Your group is comparing Tulum, Soliman Bay, Akumal, Playa del Carmen, or Puerto Aventuras.</li></ul></article></div></div></section>

	<section class="lcv-home-section lcv-home-section--alt"><div class="lcv-home-wrap"><header class="lcv-home-head"><span class="lcv-home-kicker">How It Works</span><h2 class="lcv-home-title">A simpler way to book a <em>private villa</em></h2></header><div class="lcv-steps"><div class="lcv-step"><span class="lcv-step__num">01</span><h3>Share your trip details</h3><p>Tell us your dates, group size, bedroom needs, preferred area, and service needs.</p></div><div class="lcv-step"><span class="lcv-step__num">02</span><h3>Review matched villas</h3><p>We help compare realistic options based on location, layout, service level, privacy, and fit.</p></div><div class="lcv-step"><span class="lcv-step__num">03</span><h3>Plan the stay</h3><p>Concierge planning can include airport transfers, private chef, groceries, tours, spa, diving, and activities.</p></div></div></div></section>

	<section class="lcv-home-section"><div class="lcv-home-wrap"><header class="lcv-home-head"><span class="lcv-home-kicker">Concierge Services</span><h2 class="lcv-home-title">Beyond the villa: <em>complete stay planning</em></h2><p class="lcv-home-copy">Luxury villa trips work best when the details are handled before arrival.</p></header><div class="lcv-concierge-grid"><div class="lcv-concierge-card"><h3>Airport Transfers</h3><p>Private transportation from Cancún International Airport and Cozumel arrival points.</p></div><div class="lcv-concierge-card"><h3>Private Chef</h3><p>In-villa dining, celebrations, breakfast service, and group meals.</p></div><div class="lcv-concierge-card"><h3>Diving &amp; Snorkeling</h3><p>Cozumel reefs, cenotes, Riviera Maya snorkeling, and Caribbean boat days.</p></div><div class="lcv-concierge-card"><h3>Tours &amp; Activities</h3><p>Mayan ruins, beach clubs, fishing, cenotes, ATVs, and family activities.</p></div><div class="lcv-concierge-card"><h3>Spa &amp; Wellness</h3><p>In-villa massage, wellness sessions, yoga, and relaxation services.</p></div></div></div></section>

	<section class="lcv-home-section lcv-final-cta"><div class="lcv-home-narrow"><span class="lcv-home-kicker">Start Planning</span><h2 class="lcv-home-title">Tell us what your group needs. <em>We will help narrow the search.</em></h2><p class="lcv-home-copy">Share your dates, preferred area, group size, and villa priorities. We will help identify whether a Cozumel condo or a stronger Riviera Maya villa option makes the most sense.</p><div class="lcv-home-btns"><a class="lcv-home-btn" href="<?php echo esc_url( $lvc_req ); ?>">Request Villa Matches</a><?php if ( $lvc_wa ) : ?><a class="lcv-home-btn lcv-home-btn--ghost" href="<?php echo esc_url( $lvc_wa ); ?>" target="_blank" rel="noopener">Chat on WhatsApp</a><?php endif; ?></div></div></section>
</main>
<?php get_footer(); ?>
